import DistinctionSelfReference.Core
import DistinctionSelfReference.TwoState
import DistinctionSelfReference.Dynamic
import DistinctionSelfReference.ThreeState
import DistinctionSelfReference.OrderTheoretic
