import DistinctionSelfReference.MetaFramework

namespace DistinctionSelfReference
namespace CorrigibilityDependencyGraph

open MetaFramework

/-- Independently testable conditions in the reopening/corrigibility layer. -/
inductive Condition
  | mismatchDetection
  | revisionSuccess
  | falseAlarmRejection
  | requiredRecoverability
  | continuityPreservation
  deriving DecidableEq, Repr

/-- Capabilities produced by different combinations of reopening conditions. -/
inductive Capability
  | correctMismatch
  | exactCorrection
  | recoverAfterMismatch
  | continuousCorrection
  deriving DecidableEq, Repr

def required : Capability → Set Condition
  | .correctMismatch =>
      { .mismatchDetection, .revisionSuccess }
  | .exactCorrection =>
      { .mismatchDetection, .revisionSuccess, .falseAlarmRejection }
  | .recoverAfterMismatch =>
      { .mismatchDetection, .revisionSuccess, .requiredRecoverability }
  | .continuousCorrection =>
      { .mismatchDetection, .revisionSuccess, .continuityPreservation }

/-- Capability derivability is generated by containment of its isolated requirements. -/
def graph : FrameworkGraph Condition Capability where
  derives conditions cap := required cap ⊆ conditions
  monotone := by
    intro A B cap hAB hreq
    exact Set.Subset.trans hreq hAB

/--
For this dependency presentation, each capability's declared requirement set
is inclusion-minimal for that singleton capability.
-/
theorem required_minimal (cap : Capability) :
    graph.InclusionMinimal (required cap) {cap} := by
  constructor
  · intro t ht
    change t = cap at ht
    subst t
    exact Set.Subset.rfl
  · intro smaller hsmall hsufficient
    have hreq := hsufficient (t := cap) (by rfl)
    change required cap ⊆ smaller at hreq
    rw [Set.ssubset_iff_subset_ne] at hsmall
    exact hsmall.2 (Set.Subset.antisymm hsmall.1 hreq)

theorem correctMismatch_minimal :
    graph.InclusionMinimal
      {Condition.mismatchDetection, Condition.revisionSuccess}
      {Capability.correctMismatch} := by
  simpa [required] using required_minimal Capability.correctMismatch

theorem exactCorrection_minimal :
    graph.InclusionMinimal
      {Condition.mismatchDetection, Condition.revisionSuccess,
        Condition.falseAlarmRejection}
      {Capability.exactCorrection} := by
  simpa [required] using required_minimal Capability.exactCorrection

theorem recoverAfterMismatch_minimal :
    graph.InclusionMinimal
      {Condition.mismatchDetection, Condition.revisionSuccess,
        Condition.requiredRecoverability}
      {Capability.recoverAfterMismatch} := by
  simpa [required] using required_minimal Capability.recoverAfterMismatch

theorem continuousCorrection_minimal :
    graph.InclusionMinimal
      {Condition.mismatchDetection, Condition.revisionSuccess,
        Condition.continuityPreservation}
      {Capability.continuousCorrection} := by
  simpa [required] using required_minimal Capability.continuousCorrection

end CorrigibilityDependencyGraph
end DistinctionSelfReference
