import DistinctionSelfReference.TwoState

namespace DistinctionSelfReference
namespace TwoState

/-- The orbit generated by repeated re-entry. -/
def orbit (x : Side) : ℕ → Side
  | 0 => x
  | n + 1 => cross (orbit x n)

@[simp] theorem orbit_zero (x : Side) : orbit x 0 = x := rfl

@[simp] theorem orbit_succ (x : Side) (n : ℕ) :
    orbit x (n + 1) = cross (orbit x n) := rfl

/--
Although static self-reference is impossible, dynamic re-entry is perfectly
consistent: every orbit has period two.
-/
theorem orbit_two_step (x : Side) (n : ℕ) :
    orbit x (n + 2) = orbit x n := by
  change cross (cross (orbit x n)) = orbit x n
  exact cross_involutive (orbit x n)

/-- One re-entry never returns to the same state. -/
theorem orbit_one_step_changes (x : Side) (n : ℕ) :
    orbit x (n + 1) ≠ orbit x n := by
  change cross (orbit x n) ≠ orbit x n
  exact cross_ne_self (orbit x n)

end TwoState
end DistinctionSelfReference
