name: Lean

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Elan
        run: |
          curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

      - name: Resolve dependencies
        run: lake update

      - name: Restore Mathlib cache
        run: lake exe cache get

      - name: Build
        run: lake build
